insert into groups (name, date_start, subject, leader_id) values ('Cogilith', '2020-07-26', 'Software Test Engineer II', 60);
insert into groups (name, date_start, subject, leader_id) values ('Yodel', '2014-09-13', 'Paralegal', 74);
insert into groups (name, date_start, subject, leader_id) values ('Oyoyo', '2017-10-28', 'Graphic Designer', 19);
insert into groups (name, date_start, subject, leader_id) values ('JumpXS', '2017-04-06', 'Nuclear Power Engineer', 22);
insert into groups (name, date_start, subject, leader_id) values ('Tanoodle', '2018-07-28', 'Mechanical Systems Engineer', 39);
insert into groups (name, date_start, subject, leader_id) values ('Leexo', '2019-10-30', 'Human Resources Manager', 31);
insert into groups (name, date_start, subject, leader_id) values ('Miboo', '2019-06-26', 'VP Accounting', 8);
insert into groups (name, date_start, subject, leader_id) values ('Youfeed', '2022-03-01', 'Project Manager', 12);
insert into groups (name, date_start, subject, leader_id) values ('Izio', '2020-07-11', 'Director of Sales', 97);
insert into groups (name, date_start, subject, leader_id) values ('Oyonder', '2014-12-18', 'Developer III', 6);
insert into groups (name, date_start, subject, leader_id) values ('Skynoodle', '2021-01-08', 'Senior Financial Analyst', 63);
insert into groups (name, date_start, subject, leader_id) values ('Jazzy', '2017-03-09', 'Help Desk Technician', 39);
insert into groups (name, date_start, subject, leader_id) values ('Brainlounge', '2016-06-18', 'Accounting Assistant IV', 23);
insert into groups (name, date_start, subject, leader_id) values ('Trilia', '2017-08-11', 'Web Designer IV', 75);
insert into groups (name, date_start, subject, leader_id) values ('Gabtype', '2021-08-22', 'Analog Circuit Design manager', 38);
insert into groups (name, date_start, subject, leader_id) values ('Jaxbean', '2021-08-06', 'Senior Sales Associate', 9);
insert into groups (name, date_start, subject, leader_id) values ('Babbleblab', '2016-05-19', 'Desktop Support Technician', 6);
insert into groups (name, date_start, subject, leader_id) values ('Shuffledrive', '2015-05-02', 'Structural Analysis Engineer', 27);
insert into groups (name, date_start, subject, leader_id) values ('Oyoba', '2020-10-03', 'Media Manager IV', 13);
insert into groups (name, date_start, subject, leader_id) values ('Meevee', '2024-04-05', 'Senior Financial Analyst', 30);
insert into groups (name, date_start, subject, leader_id) values ('Meedoo', '2020-11-18', 'Human Resources Manager', 21);
insert into groups (name, date_start, subject, leader_id) values ('Fivechat', '2022-03-07', 'Community Outreach Specialist', 59);
insert into groups (name, date_start, subject, leader_id) values ('Yoveo', '2016-04-24', 'Human Resources Assistant IV', 13);
insert into groups (name, date_start, subject, leader_id) values ('Realbridge', '2022-12-04', 'Product Engineer', 49);
insert into groups (name, date_start, subject, leader_id) values ('Skyvu', '2024-04-29', 'Accountant IV', 2);
insert into groups (name, date_start, subject, leader_id) values ('Kazu', '2019-06-18', 'Tax Accountant', 23);
insert into groups (name, date_start, subject, leader_id) values ('Divavu', '2020-05-04', 'Research Assistant III', 80);
insert into groups (name, date_start, subject, leader_id) values ('Eabox', '2022-11-19', 'Help Desk Technician', 10);
insert into groups (name, date_start, subject, leader_id) values ('Jetpulse', '2023-01-29', 'Computer Systems Analyst IV', 28);
insert into groups (name, date_start, subject, leader_id) values ('Gigaclub', '2024-01-08', 'Nurse Practicioner', 43);
insert into groups (name, date_start, subject, leader_id) values ('Meeveo', '2017-03-16', 'Senior Financial Analyst', 41);
insert into groups (name, date_start, subject, leader_id) values ('Pixope', '2021-06-03', 'Health Coach IV', 13);
insert into groups (name, date_start, subject, leader_id) values ('Eire', '2022-06-18', 'Internal Auditor', 16);
insert into groups (name, date_start, subject, leader_id) values ('Muxo', '2020-07-17', 'Nurse Practicioner', 75);
insert into groups (name, date_start, subject, leader_id) values ('Agimba', '2022-11-20', 'Structural Analysis Engineer', 98);
insert into groups (name, date_start, subject, leader_id) values ('Kazu', '2014-10-09', 'Internal Auditor', 4);
insert into groups (name, date_start, subject, leader_id) values ('Meembee', '2016-02-01', 'Graphic Designer', 39);
insert into groups (name, date_start, subject, leader_id) values ('Devify', '2016-05-31', 'Product Engineer', 64);
insert into groups (name, date_start, subject, leader_id) values ('Voomm', '2021-08-28', 'Web Developer III', 96);
insert into groups (name, date_start, subject, leader_id) values ('Agimba', '2014-03-16', 'Mechanical Systems Engineer', 33);
insert into groups (name, date_start, subject, leader_id) values ('Youspan', '2014-05-20', 'Computer Systems Analyst IV', 10);
insert into groups (name, date_start, subject, leader_id) values ('Jaxnation', '2016-09-09', 'Media Manager III', 74);
insert into groups (name, date_start, subject, leader_id) values ('Realpoint', '2015-02-09', 'Human Resources Assistant II', 76);
insert into groups (name, date_start, subject, leader_id) values ('Skalith', '2015-09-13', 'Research Assistant IV', 59);
insert into groups (name, date_start, subject, leader_id) values ('Kimia', '2024-07-03', 'Structural Engineer', 10);
insert into groups (name, date_start, subject, leader_id) values ('Skyndu', '2023-10-15', 'Account Coordinator', 42);
insert into groups (name, date_start, subject, leader_id) values ('Jaxspan', '2019-09-07', 'Media Manager I', 46);
insert into groups (name, date_start, subject, leader_id) values ('Quatz', '2018-09-05', 'Assistant Media Planner', 14);
insert into groups (name, date_start, subject, leader_id) values ('Thoughtstorm', '2020-02-19', 'Nuclear Power Engineer', 37);
insert into groups (name, date_start, subject, leader_id) values ('Pixonyx', '2016-08-25', 'Recruiting Manager', 51);
insert into groups (name, date_start, subject, leader_id) values ('Tagopia', '2015-09-11', 'Information Systems Manager', 78);
insert into groups (name, date_start, subject, leader_id) values ('Jazzy', '2019-04-03', 'Account Coordinator', 40);
insert into groups (name, date_start, subject, leader_id) values ('Zoomcast', '2014-05-20', 'Information Systems Manager', 50);
insert into groups (name, date_start, subject, leader_id) values ('Photojam', '2022-04-07', 'Mechanical Systems Engineer', 59);
insert into groups (name, date_start, subject, leader_id) values ('Lazz', '2022-10-27', 'VP Product Management', 79);
insert into groups (name, date_start, subject, leader_id) values ('Trudoo', '2017-01-01', 'Design Engineer', 91);
insert into groups (name, date_start, subject, leader_id) values ('Zooxo', '2022-04-28', 'VP Marketing', 53);
insert into groups (name, date_start, subject, leader_id) values ('Yodo', '2018-12-18', 'Chief Design Engineer', 99);
insert into groups (name, date_start, subject, leader_id) values ('Vimbo', '2020-09-13', 'Assistant Manager', 54);
insert into groups (name, date_start, subject, leader_id) values ('Browsedrive', '2019-03-14', 'Software Test Engineer II', 90);
insert into groups (name, date_start, subject, leader_id) values ('Kaymbo', '2023-03-27', 'Safety Technician I', 33);
insert into groups (name, date_start, subject, leader_id) values ('Riffwire', '2021-10-13', 'Assistant Media Planner', 56);
insert into groups (name, date_start, subject, leader_id) values ('Thoughtmix', '2022-02-02', 'Software Consultant', 37);
insert into groups (name, date_start, subject, leader_id) values ('Aivee', '2024-04-26', 'Professor', 80);
insert into groups (name, date_start, subject, leader_id) values ('Livefish', '2018-09-29', 'Graphic Designer', 70);
insert into groups (name, date_start, subject, leader_id) values ('Ozu', '2023-03-11', 'Marketing Assistant', 21);
insert into groups (name, date_start, subject, leader_id) values ('Voolia', '2015-08-25', 'Geological Engineer', 35);
insert into groups (name, date_start, subject, leader_id) values ('Twitterwire', '2020-03-27', 'Analog Circuit Design manager', 29);
insert into groups (name, date_start, subject, leader_id) values ('Rhyzio', '2021-05-21', 'Media Manager IV', 55);
insert into groups (name, date_start, subject, leader_id) values ('Twinder', '2024-04-06', 'Mechanical Systems Engineer', 52);
insert into groups (name, date_start, subject, leader_id) values ('Jaxnation', '2018-08-29', 'Administrative Assistant IV', 20);
insert into groups (name, date_start, subject, leader_id) values ('Realfire', '2014-03-17', 'Sales Associate', 83);
insert into groups (name, date_start, subject, leader_id) values ('Vipe', '2020-03-15', 'VP Product Management', 74);
insert into groups (name, date_start, subject, leader_id) values ('Janyx', '2014-09-05', 'Assistant Professor', 63);
insert into groups (name, date_start, subject, leader_id) values ('Blogspan', '2016-06-11', 'Research Associate', 71);
insert into groups (name, date_start, subject, leader_id) values ('Skimia', '2018-01-29', 'Statistician I', 43);
insert into groups (name, date_start, subject, leader_id) values ('Topicstorm', '2014-12-13', 'Staff Accountant IV', 18);
insert into groups (name, date_start, subject, leader_id) values ('Gevee', '2017-07-04', 'Web Designer III', 86);
insert into groups (name, date_start, subject, leader_id) values ('Photolist', '2017-10-23', 'Office Assistant III', 20);
insert into groups (name, date_start, subject, leader_id) values ('Fivespan', '2022-05-03', 'Design Engineer', 17);
insert into groups (name, date_start, subject, leader_id) values ('Edgetag', '2021-02-18', 'Analyst Programmer', 18);
insert into groups (name, date_start, subject, leader_id) values ('Bubblemix', '2020-01-04', 'Assistant Media Planner', 89);
insert into groups (name, date_start, subject, leader_id) values ('Zava', '2015-08-28', 'Administrative Officer', 41);
insert into groups (name, date_start, subject, leader_id) values ('Skipstorm', '2016-05-13', 'Junior Executive', 36);
insert into groups (name, date_start, subject, leader_id) values ('Livetube', '2022-02-24', 'Mechanical Systems Engineer', 40);
insert into groups (name, date_start, subject, leader_id) values ('Topdrive', '2014-01-16', 'Nuclear Power Engineer', 21);
insert into groups (name, date_start, subject, leader_id) values ('Riffpath', '2021-04-08', 'Web Designer III', 71);
insert into groups (name, date_start, subject, leader_id) values ('Babbleblab', '2014-03-29', 'Registered Nurse', 46);
insert into groups (name, date_start, subject, leader_id) values ('Dabvine', '2022-02-18', 'Business Systems Development Analyst', 53);
insert into groups (name, date_start, subject, leader_id) values ('Meetz', '2014-10-28', 'Nurse', 62);
insert into groups (name, date_start, subject, leader_id) values ('JumpXS', '2017-08-28', 'Librarian', 54);
insert into groups (name, date_start, subject, leader_id) values ('Feednation', '2017-12-04', 'Research Associate', 49);
insert into groups (name, date_start, subject, leader_id) values ('Jabberbean', '2021-08-30', 'Help Desk Operator', 8);
insert into groups (name, date_start, subject, leader_id) values ('Zoomcast', '2018-03-12', 'Chief Design Engineer', 96);
insert into groups (name, date_start, subject, leader_id) values ('Divape', '2021-03-19', 'Research Assistant I', 69);
insert into groups (name, date_start, subject, leader_id) values ('Yakidoo', '2014-03-08', 'Help Desk Operator', 63);
insert into groups (name, date_start, subject, leader_id) values ('Devpulse', '2022-12-11', 'Research Nurse', 21);
insert into groups (name, date_start, subject, leader_id) values ('Buzzster', '2021-07-04', 'Tax Accountant', 25);
insert into groups (name, date_start, subject, leader_id) values ('Skyvu', '2015-04-24', 'Community Outreach Specialist', 53);
insert into groups (name, date_start, subject, leader_id) values ('Roodel', '2024-06-01', 'Executive Secretary', 30);
